# resnet50 fpn voc
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  FCOS:
    NUM_CLASSES: 2
    PRE_NMS_TOP_N: 1000
    NUM_CONVS: 1
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: 0
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    TRANS_FUNC: "BottleneckWithBatchNorm"
    STEM_FUNC: "StemWithBatchNorm"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
  MIX_BG: False
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 1333
  IMGAUG: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 12
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
