MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN_ONLY: True
  FCOS_ON: True
  FCOS:
    NUM_CLASSES: 2
    PRE_NMS_TOP_N: 400
    NUM_CONVS: 1
  BACKBONE:
    CONV_BODY: "EFFICIENTNET-B3-HRFPN-RETINANET"
    FREEZE_CONV_BODY_AT: 0
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 1333
  IMGAUG: True
DATALOADER:
  SIZE_DIVISIBILITY: 16
SOLVER:
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
  CHECKPOINT_PERIOD: 10000
